# Example: Validate skills but don't fail the workflow (warning mode)

name: Validate Skills (Warning Only)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  validate:
    name: Validate Skills
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Skill Doctor
        uses: tcarac/skill-doctor@v1
        with:
          path: 'skills/*'
          mode: 'multiple'
          fail-on-error: false  # Don't fail workflow
          comment-on-pr: true
          create-annotations: true

      - name: Continue with other steps
        run: echo "Workflow continues regardless of validation results"
