name: 'Skill Doctor'
description: 'Validate Agent Skills against the official specification with helpful diagnostics'
author: 'Tomas Caraccia'

branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  path:
    description: 'Path to skill directory or glob pattern (e.g., skills/*)'
    required: false
    default: '.'

  mode:
    description: 'Validation mode: single, multiple, or changed'
    required: false
    default: 'single'

  fail-on-error:
    description: 'Whether to fail the workflow on validation errors'
    required: false
    default: 'true'

  comment-on-pr:
    description: 'Post validation results as PR comment'
    required: false
    default: 'true'

  create-annotations:
    description: 'Create GitHub annotations for errors'
    required: false
    default: 'true'

  auto-fix-suggestions:
    description: 'Include auto-fix suggestions in output'
    required: false
    default: 'true'

  output-json:
    description: 'Output results as JSON artifact'
    required: false
    default: 'false'

  github-token:
    description: 'GitHub token for API access (default: github.token)'
    required: false
    default: ${{ github.token }}

outputs:
  validation-status:
    description: 'Overall validation status: passed, failed, or warning'

  skills-validated:
    description: 'Number of skills validated'

  errors-found:
    description: 'Total number of errors found'

  json-results:
    description: 'Path to JSON results file (if output-json is enabled)'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --path=${{ inputs.path }}
    - --mode=${{ inputs.mode }}
    - --fail-on-error=${{ inputs.fail-on-error }}
    - --comment-on-pr=${{ inputs.comment-on-pr }}
    - --create-annotations=${{ inputs.create-annotations }}
    - --auto-fix-suggestions=${{ inputs.auto-fix-suggestions }}
    - --output-json=${{ inputs.output-json }}
    - --github-token=${{ inputs.github-token }}
